$LOAD_PATH.unshift(File.join(File.dirname(__FILE__),'..', '..', '..', '..', 'lib'))
require 'rbbt/sources/biomart'
require 'rbbt/sources/entrez'

$interpro_db = 'entry'

$interpro_id = ['InterPro Entry Accession','entry_id']

$interpro_pos = [
  ["UniProt/SwissProt Accession", "protein_ac"],
  ["Match Start Position", "pos_from"],
  ["Match Stop Position ", "pos_to"]
]

file 'interpro_positions' do |t|
  Open.write(t.name, InterPro.tsv($interpro_db, $interpro_id, $interpro_pos, [], nil, :type => :double, :nocache => true).to_s)
end

file 'interpro_names' do |t|
  Open.write(t.name, "#: :type=:list\n#InterPro Entry Accession\tName\n" +  Open.read("ftp://ftp.ebi.ac.uk/pub/databases/interpro/names.dat"))
end


file 'interpro_short_names' do |t|
  Open.write(t.name,  "#: :type=:list\n#InterPro Entry Accession\tShort Name\n" +  Open.read("ftp://ftp.ebi.ac.uk/pub/databases/interpro/short_names.dat"))
end



