$LOAD_PATH.unshift(File.join(File.dirname(__FILE__),'..', '..', '..', '..', 'lib'))
require 'rbbt/sources/biomart'
require 'rbbt/sources/entrez'
require File.join(File.dirname(__FILE__), '../../lib/helpers')

$taxs = [559292,4932]
$scientific_name = "Saccharomyces cerevisiae"
#$ortholog_key = "yeast_ensembl_gene"

$biomart_db = 'scerevisiae_gene_ensembl'

$biomart_lexicon = [ 
  [ 'Associated Gene Name' , "external_gene_name"], 
]

$biomart_protein_identifiers = [
  [ 'Protein ID', "protein_id"  ],
  [ 'RefSeq Protein ID', "refseq_peptide"  ],
  [ 'Unigene ID', "unigene"  ],
  [ 'UniProt/SwissProt ID', "uniprot_swissprot"  ],
  [ 'UniProt/SwissProt Accession', "uniprot_swissprot_accession"  ],
]

$biomart_probe_identifiers = [
]

$biomart_identifiers = [ 
  [ 'Entrez Gene ID', "entrezgene"],
  [ 'Ensembl Protein ID', "ensembl_peptide_id"  ],
  [ 'Associated Gene Name', "external_gene_name"  ],
  [ 'Protein ID', "protein_id"  ],
  [ 'RefSeq Protein ID', "refseq_peptide"  ],
  [ 'UniProt/SwissProt ID', "uniprot_swissprot"  ],
  [ 'UniProt/SwissProt Accession', "uniprot_swissprot_accession"  ],
  [ 'EMBL (Genbank) ID' , "embl"] , 
  #[ 'RefSeq mRNA' , "refseq_mrna"] , 
]

$biomart_go= [
  ["GO ID", 'go_id'],
  ["GO Namespace", 'namespace_1003'],
]

$biomart_go_2009= [
  ["GO BP ID", 'go_biological_process_id'],
  ["GO MF ID", 'go_molecular_function_id'],
  ["GO CC ID", 'go_cellular_component_id'],
]

$namespace = File.basename(File.dirname(File.expand_path(__FILE__)))
Thread.current["namespace"] = File.basename(File.dirname(File.expand_path(__FILE__)))
load File.join(File.dirname(__FILE__), '../organism_helpers.rb')
