$LOAD_PATH.unshift(File.join(File.dirname(__FILE__),'..', '..', '..', '..', 'lib'))
require 'rbbt/sources/biomart'
require 'rbbt/sources/entrez'
require File.join(File.dirname(__FILE__), '../../lib/helpers')

$taxs = [9606]
$scientific_name = "Homo sapiens"

$biomart_db = 'hsapiens_gene_ensembl'
$biomart_db_germline_variation = 'hsapiens_snp'
$biomart_db_somatic_variation = 'hsapiens_snp_som'

$biomart_lexicon = [ 
  [ 'Associated Gene Name' , "external_gene_id"], 
  [ 'HGNC symbol', "hgnc_symbol"  ],
  [ 'HGNC automatic gene name', "hgnc_automatic_gene_name"  ],
  [ 'HGNC curated gene name ', "hgnc_curated_gene_name"  ],
]

$biomart_protein_identifiers = [
  [ 'Protein ID', "protein_id"  ],
  [ 'RefSeq Protein ID', "refseq_peptide"  ],
  [ 'Unigene ID', "unigene"  ],
  [ 'UniProt/SwissProt ID', "uniprot_swissprot"  ],
  [ 'UniProt/SwissProt Accession', "uniprot_swissprot_accession"  ],
]

$biomart_probe_identifiers = [
  [ 'AFFY HC G110', 'affy_hc_g110' ],
  [ 'AFFY HG FOCUS', 'affy_hg_focus' ],
  [ 'AFFY HG U133-PLUS-2', 'affy_hg_u133_plus_2' ],
  [ 'AFFY HG U133A_2', 'affy_hg_u133a_2' ],
  [ 'AFFY HG U133A', 'affy_hg_u133a' ],
  [ 'AFFY HG U133B', 'affy_hg_u133b' ],
  [ 'AFFY HG U95AV2', 'affy_hg_u95av2' ],
  [ 'AFFY HG U95B', 'affy_hg_u95b' ],
  [ 'AFFY HG U95C', 'affy_hg_u95c' ],
  [ 'AFFY HG U95D', 'affy_hg_u95d' ],
  [ 'AFFY HG U95E', 'affy_hg_u95e' ],
  [ 'AFFY HG U95A', 'affy_hg_u95a' ],
  [ 'AFFY HUGENEFL', 'affy_hugenefl' ],
  [ 'AFFY HuEx', 'affy_huex_1_0_st_v2', "HuEx" ],
  [ 'AFFY HuGene', 'affy_hugene_1_0_st_v1' ],
  [ 'AFFY U133 X3P', 'affy_u133_x3p' ],
  [ 'Agilent WholeGenome',"agilent_wholegenome" ],
  [ 'Agilent CGH 44b', 'agilent_cgh_44b' ],
  [ 'Codelink ID', 'codelink' ],
  [ 'Illumina HumanWG 6 v2', 'illumina_humanwg_6_v2' ],
  [ 'Illumina HumanWG 6 v3', 'illumina_humanwg_6_v3' ],
]

$biomart_identifiers = [ 
  [ 'Entrez Gene ID', "entrezgene"],
  [ 'Ensembl Protein ID', "ensembl_peptide_id"  ],
  [ 'Associated Gene Name', "external_gene_id"  ],
  [ 'CCDS ID', "ccds"  ],
  [ 'Protein ID', "protein_id"  ],
  [ 'RefSeq Protein ID', "refseq_peptide"  ],
  [ 'Unigene ID', "unigene"  ],
  [ 'UniProt/SwissProt ID', "uniprot_swissprot"  ],
  [ 'UniProt/SwissProt Accession', "uniprot_swissprot_accession"  ],
  [ 'HGNC ID', "hgnc_id", 'HGNC'],
  [ 'EMBL (Genbank) ID' , "embl"] , 

  # Probes
  [ 'AFFY HC G110', 'affy_hc_g110' ],
  [ 'AFFY HG FOCUS', 'affy_hg_focus' ],
  [ 'AFFY HG U133-PLUS-2', 'affy_hg_u133_plus_2' ],
  [ 'AFFY HG U133A_2', 'affy_hg_u133a_2' ],
  [ 'AFFY HG U133A', 'affy_hg_u133a' ],
  [ 'AFFY HG U133B', 'affy_hg_u133b' ],
  [ 'AFFY HG U95AV2', 'affy_hg_u95av2' ],
  [ 'AFFY HG U95B', 'affy_hg_u95b' ],
  [ 'AFFY HG U95C', 'affy_hg_u95c' ],
  [ 'AFFY HG U95D', 'affy_hg_u95d' ],
  [ 'AFFY HG U95E', 'affy_hg_u95e' ],
  [ 'AFFY HG U95A', 'affy_hg_u95a' ],
  [ 'AFFY HUGENEFL', 'affy_hugenefl' ],
  [ 'AFFY HuEx', 'affy_huex_1_0_st_v2', "HuEx" ],
  [ 'AFFY HuGene', 'affy_hugene_1_0_st_v1' ],
  [ 'AFFY U133 X3P', 'affy_u133_x3p' ],
  [ 'Agilent WholeGenome',"agilent_wholegenome" ],
  [ 'Agilent CGH 44b', 'agilent_cgh_44b' ],
  [ 'Codelink ID', 'codelink' ],
  [ 'Illumina HumanWG 6 v2', 'illumina_humanwg_6_v2' ],
  [ 'Illumina HumanWG 6 v3', 'illumina_humanwg_6_v3' ],
]

$biomart_go= [
  ["GO ID", 'go_id'],
  ["GO Namespace", 'namespace_1003'],
]

$biomart_pfam= [
  ["Pfam Domain", 'pfam'],
]

$namespace = File.basename(File.dirname(File.expand_path(__FILE__)))
load File.join(File.dirname(__FILE__), '../organism_helpers.rb')
